defmodule Edenflowers.Repo.Migrations.AddUsageColumn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :promotion_claimed
    end

    alter table(:promotions) do
      add :usage, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:promotions) do
      remove :usage
    end

    alter table(:users) do
      add :promotion_claimed, :boolean, default: false
    end
  end
end
