defmodule Edenflowers.Repo.Migrations.AddImageToProduct do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :image, :text, null: false
    end
  end

  def down do
    alter table(:products) do
      remove :image
    end
  end
end
