defmodule Edenflowers.Repo.Migrations.Order do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :here_id, :text
      add :distance, :bigint
    end
  end

  def down do
    alter table(:orders) do
      remove :distance
      remove :here_id
    end
  end
end
