defmodule Edenflowers.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :newsletter_opt_in, :boolean, default: false
      add :promotion_claimed, :boolean, default: false
    end

    alter table(:promotions) do
      add :usage_limit, :bigint
    end
  end

  def down do
    alter table(:promotions) do
      remove :usage_limit
    end

    alter table(:users) do
      remove :promotion_claimed
      remove :newsletter_opt_in
    end
  end
end
