defmodule Edenflowers.Repo.Migrations.ModifyOrder do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      modify :product_category_id, :uuid, null: false
    end

    rename table(:orders), :payment_state, to: :payment_status

    rename table(:orders), :fulfillment_state, to: :fulfillment_status

    alter table(:fulfillment_options) do
      modify :order_deadline, :time, default: nil
    end
  end

  def down do
    alter table(:fulfillment_options) do
      modify :order_deadline, :time, default: fragment("'14:00:00'")
    end

    rename table(:orders), :fulfillment_status, to: :fulfillment_state

    rename table(:orders), :payment_status, to: :payment_state

    alter table(:products) do
      modify :product_category_id, :uuid, null: true
    end
  end
end
