defmodule Edenflowers.Repo.Migrations.AddAdminToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :admin, :boolean, default: false
    end

    alter table(:orders) do
      modify :locale, :text, default: "sv-FI"
    end
  end

  def down do
    alter table(:orders) do
      modify :locale, :text, default: nil
    end

    alter table(:users) do
      remove :admin
    end
  end
end
