defmodule Edenflowers.Repo.Migrations.AddSlugAndDraftToProductCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:product_categories) do
      add :slug, :text, null: false
      add :draft, :boolean, null: false, default: true
    end

    create unique_index(:product_categories, [:slug],
             name: "product_categories_unique_slug_index"
           )
  end

  def down do
    drop_if_exists unique_index(:product_categories, [:slug],
                     name: "product_categories_unique_slug_index"
                   )

    alter table(:product_categories) do
      remove :draft
      remove :slug
    end
  end
end
