defmodule Edenflowers.Repo.Migrations.Migrate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:product_categories) do
      add :translations, :map
    end
  end

  def down do
    alter table(:product_categories) do
      remove :translations
    end
  end
end
