defmodule Edenflowers.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:orders), :stripe_payment_id, to: :payment_intent_id
  end

  def down do
    rename table(:orders), :payment_intent_id, to: :stripe_payment_id
  end
end
