defmodule Edenflowers.Repo.Migrations.Order do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:orders), :recipient_address, to: :delivery_address

    alter table(:orders) do
      modify :delivery_address, :text
    end
  end

  def down do
    alter table(:orders) do
      modify :recipient_address, :text
    end

    rename table(:orders), :delivery_address, to: :recipient_address
  end
end
