defmodule Edenflowers.Repo.Migrations.AddDraftAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :draft, :boolean, null: false, default: true
    end

    alter table(:product_variants) do
      add :draft, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:product_variants) do
      remove :draft
    end

    alter table(:products) do
      remove :draft
    end
  end
end
