defmodule Edenflowers.Repo.Migrations.CascadeDeleteChatMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:messages, "messages_conversation_id_fkey")

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:messages, "messages_response_to_id_fkey")

    alter table(:messages) do
      modify :response_to_id,
             references(:messages,
               column: :id,
               name: "messages_response_to_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:messages, "messages_response_to_id_fkey")

    drop constraint(:messages, "messages_conversation_id_fkey")

    alter table(:messages) do
      modify :response_to_id,
             references(:messages,
               column: :id,
               name: "messages_response_to_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
