defmodule Edenflowers.Repo.Migrations.AddFreeDelivery do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:line_items) do
      add :free_delivery, :boolean, null: false, default: false
    end

    alter table(:products) do
      add :free_delivery, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:products) do
      remove :free_delivery
    end

    alter table(:line_items) do
      remove :free_delivery
    end
  end
end
