defmodule Edenflowers.Repo.Migrations.MoveCardMessageToOrder do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :card_message, :text
    end

    alter table(:line_items) do
      remove :card_message
    end
  end

  def down do
    alter table(:line_items) do
      add :card_message, :text
    end

    alter table(:orders) do
      remove :card_message
    end
  end
end
