defmodule Edenflowers.Repo.Migrations.RecordStopOutcome do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:route_stops) do
      add :delivery_method, :text
      add :failure_reason, :text
      add :outcome_note, :text
      add :outcome_recorded_at, :utc_datetime
    end
  end

  def down do
    alter table(:route_stops) do
      remove :outcome_recorded_at
      remove :outcome_note
      remove :failure_reason
      remove :delivery_method
    end
  end
end
