defmodule Edenflowers.Repo.Migrations.AddTranslations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:courses) do
      add :translations, :map
    end

    alter table(:fulfillment_options) do
      add :translations, :map
    end

    alter table(:products) do
      add :translations, :map
    end
  end

  def down do
    alter table(:products) do
      remove :translations
    end

    alter table(:fulfillment_options) do
      remove :translations
    end

    alter table(:courses) do
      remove :translations
    end
  end
end
