defmodule Edenflowers.Repo.Migrations.AddUniqueOrderReference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:orders, [:order_reference], name: "orders_unique_order_reference_index")
  end

  def down do
    drop_if_exists unique_index(:orders, [:order_reference],
                     name: "orders_unique_order_reference_index"
                   )
  end
end
