defmodule Edenflowers.Repo.Migrations.AddCourseBooking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:course_registrations) do
      add :seats, :bigint, null: false, default: 1
      add :locale, :text, null: false, default: "sv-FI"
      add :reference, :text, null: false
      add :unit_price, :decimal, null: false
      add :tax_rate, :decimal, null: false
      add :amount, :decimal, null: false
      add :payment_intent_id, :text
      add :confirmed_at, :utc_datetime
      add :receipt_emailed_at, :utc_datetime
      add :receipt_sha256, :text
      modify :course_id, :uuid, null: false
    end

    alter table(:courses) do
      add :tax_rate_id,
          references(:tax_rates,
            column: :id,
            name: "courses_tax_rate_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    # Any course created before courses carried a tax rate takes the rate most
    # products use, so the NOT NULL below can't fail on existing rows.
    execute """
    UPDATE courses SET tax_rate_id = (
      SELECT tax_rate_id FROM products GROUP BY tax_rate_id ORDER BY count(*) DESC LIMIT 1
    )
    WHERE tax_rate_id IS NULL
    """

    alter table(:courses) do
      modify :tax_rate_id, :uuid, null: false
    end
  end

  def down do
    drop constraint(:courses, "courses_tax_rate_id_fkey")

    alter table(:courses) do
      remove :tax_rate_id
    end

    alter table(:course_registrations) do
      modify :course_id, :uuid, null: true
      remove :receipt_sha256
      remove :receipt_emailed_at
      remove :confirmed_at
      remove :payment_intent_id
      remove :amount
      remove :tax_rate
      remove :unit_price
      remove :reference
      remove :locale
      remove :seats
    end
  end
end
