defmodule Edenflowers.Repo.Migrations.SnapshotPromotionMinimum do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :promotion_minimum_cart_total, :decimal
    end
  end

  def down do
    alter table(:orders) do
      remove :promotion_minimum_cart_total
    end
  end
end
