defmodule Edenflowers.Repo.Migrations.AddSubscriptionOccurrences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :subscription_date, :date
    end

    create unique_index(:orders, [:subscription_id, :subscription_date],
             name: "orders_unique_occurrence_index"
           )
  end

  def down do
    drop_if_exists unique_index(:orders, [:subscription_id, :subscription_date],
                     name: "orders_unique_occurrence_index"
                   )

    alter table(:orders) do
      remove :subscription_date
    end
  end
end
