defmodule Edenflowers.Repo.Migrations.AddUserAvatar do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :avatar, :binary
      add :avatar_content_type, :text
    end
  end

  def down do
    alter table(:users) do
      remove :avatar_content_type
      remove :avatar
    end
  end
end
