defmodule Edenflowers.Repo.Migrations.AddPaymentMethodDetails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:course_registrations) do
      add :payment_method_type, :text
      add :card_brand, :text
      add :card_last4, :text
    end

    alter table(:payments) do
      add :payment_method_type, :text
      add :card_brand, :text
      add :card_last4, :text
    end
  end

  def down do
    alter table(:payments) do
      remove :card_last4
      remove :card_brand
      remove :payment_method_type
    end

    alter table(:course_registrations) do
      remove :card_last4
      remove :card_brand
      remove :payment_method_type
    end
  end
end
