defmodule Edenflowers.Repo.Migrations.RemoveSqidsAddOrderReference do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      remove :order_number
      add :order_reference, :text
    end
  end

  def down do
    alter table(:orders) do
      remove :order_reference
      add :order_number, :bigserial, null: false
    end
  end
end
