defmodule Edenflowers.Repo.Migrations.AddFulfillmentMethodToOrders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :fulfillment_method, :text
    end
  end

  def down do
    alter table(:orders) do
      remove :fulfillment_method
    end
  end
end
