defmodule Edenflowers.Repo.Migrations.RefactorNamingAndAvailableDays do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:fulfillment_options) do
      remove :sunday
      remove :saturday
      remove :friday
      remove :thursday
      remove :wednesday
      remove :tuesday
      remove :monday
      add :available_days, {:array, :text}
    end
  end

  def down do
    alter table(:fulfillment_options) do
      remove :available_days
      add :monday, :boolean, default: true
      add :tuesday, :boolean, default: true
      add :wednesday, :boolean, default: true
      add :thursday, :boolean, default: true
      add :friday, :boolean, default: true
      add :saturday, :boolean, default: true
      add :sunday, :boolean, default: false
    end
  end
end
