defmodule Edenflowers.Repo.Migrations.PersistVatBreakdown do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :vat_breakdown, {:array, :map}
    end

    create constraint(:product_variants, :product_variants_valid_price,
             check: "price >= 0 AND price = round(price, 2)"
           )
  end

  def down do
    drop constraint(:product_variants, :product_variants_valid_price)

    alter table(:orders) do
      remove :vat_breakdown
    end
  end
end
