defmodule Edenflowers.Repo.Migrations.AddCardSizeToLineItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:line_items) do
      add :card_size, :text
    end
  end

  def down do
    alter table(:line_items) do
      remove :card_size
    end
  end
end
