defmodule Edenflowers.Repo.Migrations.AddCardMessageToLineItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      remove :gift_message
    end

    alter table(:line_items) do
      add :card_message, :text
      add :is_card, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:line_items) do
      remove :is_card
      remove :card_message
    end

    alter table(:orders) do
      add :gift_message, :text
    end
  end
end
