defmodule Edenflowers.Repo.Migrations.AddSubscriptionVersionActor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subscriptions_versions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "subscriptions_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:subscriptions_versions, "subscriptions_versions_user_id_fkey")

    alter table(:subscriptions_versions) do
      remove :user_id
    end
  end
end
