defmodule Edenflowers.Repo.Migrations.RemovePromotionUsageCounter do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      remove :promotion_usage_counted_at
    end

    alter table(:promotions) do
      remove :usage
    end
  end

  def down do
    alter table(:promotions) do
      add :usage, :bigint, null: false, default: 0
    end

    alter table(:orders) do
      add :promotion_usage_counted_at, :utc_datetime
    end
  end
end
