defmodule Edenflowers.Repo.Migrations.AddSubscriptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:line_items) do
      add :subscribable, :boolean, null: false, default: false
    end

    alter table(:orders) do
      add :subscription_interval_weeks, :bigint
      add :subscription_id, :uuid
    end

    alter table(:products) do
      add :subscribable, :boolean, null: false, default: false
    end

    create table(:subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders) do
      modify :subscription_id,
             references(:subscriptions,
               column: :id,
               name: "orders_subscription_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:subscriptions) do
      add :interval_weeks, :bigint, null: false
      add :next_fulfillment_date, :date, null: false
      add :recipient_name, :text
      add :recipient_phone_number, :text
      add :delivery_address, :text
      add :delivery_instructions, :text
      add :card_message, :text
      add :locale, :text, null: false
      add :stripe_customer_id, :text, null: false
      add :stripe_payment_method_id, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "active"

      add :user_id,
          references(:users,
            column: :id,
            name: "subscriptions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :product_variant_id,
          references(:product_variants,
            column: :id,
            name: "subscriptions_product_variant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :fulfillment_option_id,
          references(:fulfillment_options,
            column: :id,
            name: "subscriptions_fulfillment_option_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:subscriptions_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false

      add :version_source_id,
          references(:subscriptions,
            column: :id,
            name: "subscriptions_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:subscriptions_versions, "subscriptions_versions_version_source_id_fkey")

    drop table(:subscriptions_versions)

    drop constraint(:subscriptions, "subscriptions_fulfillment_option_id_fkey")

    drop constraint(:subscriptions, "subscriptions_product_variant_id_fkey")

    drop constraint(:subscriptions, "subscriptions_user_id_fkey")

    alter table(:subscriptions) do
      remove :fulfillment_option_id
      remove :product_variant_id
      remove :user_id
      remove :state
      remove :updated_at
      remove :inserted_at
      remove :stripe_payment_method_id
      remove :stripe_customer_id
      remove :locale
      remove :card_message
      remove :delivery_instructions
      remove :delivery_address
      remove :recipient_phone_number
      remove :recipient_name
      remove :next_fulfillment_date
      remove :interval_weeks
    end

    drop constraint(:orders, "orders_subscription_id_fkey")

    alter table(:orders) do
      modify :subscription_id, :uuid
    end

    drop table(:subscriptions)

    alter table(:products) do
      remove :subscribable
    end

    alter table(:orders) do
      remove :subscription_id
      remove :subscription_interval_weeks
    end

    alter table(:line_items) do
      remove :subscribable
    end
  end
end
