defmodule Edenflowers.Repo.Migrations.SequentialReferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:course_registrations, [:reference],
             name: "course_registrations_unique_reference_index"
           )

    execute("""
    CREATE SEQUENCE reference_seq START 1400
    """)
  end

  def down do
    execute("""
    DROP SEQUENCE reference_seq
    """)

    drop_if_exists unique_index(:course_registrations, [:reference],
                     name: "course_registrations_unique_reference_index"
                   )
  end
end
