defmodule Edenflowers.Repo.Migrations.StandardizeMoneyPrecision do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:expenses, :expenses_valid_total_amount,
             check: """
               total_amount = round(total_amount, 2)
             """
           )

    create constraint(:expenses, :expenses_valid_vat_amount,
             check: """
               vat_amount = round(vat_amount, 2)
             """
           )

    create constraint(:fulfillment_options, :fulfillment_options_valid_minimum_cart_total,
             check: """
               minimum_cart_total >= 0 AND minimum_cart_total = round(minimum_cart_total, 2)
             """
           )

    create constraint(:fulfillment_options, :fulfillment_options_valid_base_price,
             check: """
               base_price >= 0 AND base_price = round(base_price, 2)
             """
           )

    create constraint(:fulfillment_options, :fulfillment_options_valid_price_per_km,
             check: """
               price_per_km >= 0 AND price_per_km = round(price_per_km, 2)
             """
           )

    create constraint(:line_items, :line_items_valid_unit_price,
             check: """
               unit_price >= 0 AND unit_price = round(unit_price, 2)
             """
           )

    create constraint(:orders, :orders_valid_fulfillment_fee,
             check: """
               fulfillment_fee >= 0 AND fulfillment_fee = round(fulfillment_fee, 2)
             """
           )

    create constraint(:orders, :orders_valid_amount_paid,
             check: """
               amount_paid >= 0 AND amount_paid = round(amount_paid, 2)
             """
           )

    create constraint(:orders, :orders_paid_requires_amount,
             check: """
               payment_status != 'paid' OR amount_paid IS NOT NULL
             """
           )

    create constraint(:promotions, :promotions_valid_minimum_cart_total,
             check: """
               minimum_cart_total >= 0 AND minimum_cart_total = round(minimum_cart_total, 2)
             """
           )
  end

  def down do
    drop_if_exists constraint(:promotions, :promotions_valid_minimum_cart_total)

    drop_if_exists constraint(:orders, :orders_paid_requires_amount)

    drop_if_exists constraint(:orders, :orders_valid_amount_paid)

    drop_if_exists constraint(:orders, :orders_valid_fulfillment_fee)

    drop_if_exists constraint(:line_items, :line_items_valid_unit_price)

    drop_if_exists constraint(:fulfillment_options, :fulfillment_options_valid_price_per_km)

    drop_if_exists constraint(:fulfillment_options, :fulfillment_options_valid_base_price)

    drop_if_exists constraint(:fulfillment_options, :fulfillment_options_valid_minimum_cart_total)

    drop_if_exists constraint(:expenses, :expenses_valid_vat_amount)

    drop_if_exists constraint(:expenses, :expenses_valid_total_amount)
  end
end
