defmodule Edenflowers.Repo.Migrations.SnapshotPromotionNameCodeAndFulfillmentOptionName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :fulfillment_option_name, :text
      add :promotion_name, :text
      add :promotion_code, :text
    end
  end

  def down do
    alter table(:orders) do
      remove :promotion_code
      remove :promotion_name
      remove :fulfillment_option_name
    end
  end
end
