defmodule Edenflowers.Repo.Migrations.ConstrainCourseMoneyPrecision do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:course_registrations, :course_registrations_valid_amount,
             check: """
               amount >= 0 AND amount = round(amount, 2)
             """
           )

    create constraint(:courses, :courses_valid_price,
             check: """
               price >= 0 AND price = round(price, 2)
             """
           )
  end

  def down do
    drop_if_exists constraint(:courses, :courses_valid_price)

    drop_if_exists constraint(:course_registrations, :course_registrations_valid_amount)
  end
end
