defmodule Edenflowers.Repo.Migrations.AddNewsletterOfferHiddenToOrders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :newsletter_offer_hidden?, :boolean, default: false
    end
  end

  def down do
    alter table(:orders) do
      remove :newsletter_offer_hidden?
    end
  end
end
