defmodule Edenflowers.Repo.Migrations.AddDeliveryDispatch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:expenses) do
      modify :updated_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
      modify :inserted_at, :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:drivers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :email, :citext, null: false
      add :preferred_locale, :text, null: false, default: "en-GB"
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:drivers, [:email], name: "drivers_unique_email_index")

    create table(:delivery_trips, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sequence, :bigint, null: false
      add :distance, :bigint, null: false
      add :driving_duration, :bigint, null: false
      add :service_duration, :bigint, null: false
      add :return_leg_distance, :bigint
      add :return_leg_duration, :bigint
      add :published_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :delivery_route_id, :uuid, null: false
      add :batch_id, :uuid, null: false
    end

    create unique_index(:delivery_trips, [:delivery_route_id, :sequence],
             name: "delivery_trips_unique_route_sequence_index"
           )

    create table(:delivery_stops, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sequence, :bigint, null: false
      add :leg_distance, :bigint, null: false
      add :leg_duration, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :delivery_trip_id,
          references(:delivery_trips,
            column: :id,
            name: "delivery_stops_delivery_trip_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :order_id,
          references(:orders,
            column: :id,
            name: "delivery_stops_order_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:delivery_stops, [:delivery_trip_id, :sequence],
             name: "delivery_stops_unique_trip_sequence_index"
           )

    create index(:delivery_stops, [:order_id])

    create table(:delivery_routes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:delivery_trips) do
      modify :delivery_route_id,
             references(:delivery_routes,
               column: :id,
               name: "delivery_trips_delivery_route_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:delivery_routes) do
      add :delivery_date, :date, null: false
      add :token_hash, :text
      add :first_published_at, :utc_datetime
      add :first_email_queued_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :driver_id,
          references(:drivers,
            column: :id,
            name: "delivery_routes_driver_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:delivery_routes, [:driver_id, :delivery_date],
             name: "delivery_routes_unique_driver_date_index"
           )

    create unique_index(:delivery_routes, [:token_hash],
             name: "delivery_routes_unique_token_hash_index"
           )

    create table(:delivery_batches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:delivery_trips) do
      modify :batch_id,
             references(:delivery_batches,
               column: :id,
               name: "delivery_trips_batch_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:delivery_batches) do
      add :delivery_date, :date, null: false
      add :published_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :published_by_user_id,
          references(:users,
            column: :id,
            name: "delivery_batches_published_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:delivery_attempts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :outcome, :text, null: false
      add :delivered_method, :text
      add :failure_reason, :text
      add :note, :text
      add :recorded_at, :utc_datetime, null: false
      add :actor_kind, :text, null: false
      add :photo_path, :text
      add :photo_media_type, :text
      add :photo_original_filename, :text
      add :photo_byte_size, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :delivery_stop_id,
          references(:delivery_stops,
            column: :id,
            name: "delivery_attempts_delivery_stop_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :recorded_by_user_id,
          references(:users,
            column: :id,
            name: "delivery_attempts_recorded_by_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:delivery_attempts, "delivery_attempts_delivery_stop_id_fkey")

    drop constraint(:delivery_attempts, "delivery_attempts_recorded_by_user_id_fkey")

    drop table(:delivery_attempts)

    drop constraint(:delivery_batches, "delivery_batches_published_by_user_id_fkey")

    alter table(:delivery_batches) do
      remove :published_by_user_id
      remove :updated_at
      remove :inserted_at
      remove :published_at
      remove :delivery_date
    end

    drop constraint(:delivery_trips, "delivery_trips_batch_id_fkey")

    alter table(:delivery_trips) do
      modify :batch_id, :uuid
    end

    drop table(:delivery_batches)

    drop constraint(:delivery_routes, "delivery_routes_driver_id_fkey")

    drop_if_exists unique_index(:delivery_routes, [:token_hash],
                     name: "delivery_routes_unique_token_hash_index"
                   )

    drop_if_exists unique_index(:delivery_routes, [:driver_id, :delivery_date],
                     name: "delivery_routes_unique_driver_date_index"
                   )

    alter table(:delivery_routes) do
      remove :driver_id
      remove :updated_at
      remove :inserted_at
      remove :first_email_queued_at
      remove :first_published_at
      remove :token_hash
      remove :delivery_date
    end

    drop constraint(:delivery_trips, "delivery_trips_delivery_route_id_fkey")

    alter table(:delivery_trips) do
      modify :delivery_route_id, :uuid
    end

    drop table(:delivery_routes)

    drop_if_exists index(:delivery_stops, [:order_id])

    drop constraint(:delivery_stops, "delivery_stops_delivery_trip_id_fkey")

    drop constraint(:delivery_stops, "delivery_stops_order_id_fkey")

    drop_if_exists unique_index(:delivery_stops, [:delivery_trip_id, :sequence],
                     name: "delivery_stops_unique_trip_sequence_index"
                   )

    drop table(:delivery_stops)

    drop_if_exists unique_index(:delivery_trips, [:delivery_route_id, :sequence],
                     name: "delivery_trips_unique_route_sequence_index"
                   )

    drop table(:delivery_trips)

    drop_if_exists unique_index(:drivers, [:email], name: "drivers_unique_email_index")

    drop table(:drivers)

    alter table(:expenses) do
      modify :inserted_at, :utc_datetime, default: nil
      modify :updated_at, :utc_datetime, default: nil
    end
  end
end
