defmodule Edenflowers.Repo.Migrations.RenameCalculatedAddressToGeocodedAddress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      remove :calculated_address
      add :geocoded_address, :text
    end
  end

  def down do
    alter table(:orders) do
      remove :geocoded_address
      add :calculated_address, :text
    end
  end
end
