defmodule Edenflowers.Repo.Migrations.RenameFulfillmentTaxRate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:orders), :fulfillment_tax_percentage, to: :fulfillment_tax_rate
  end

  def down do
    rename table(:orders), :fulfillment_tax_rate, to: :fulfillment_tax_percentage
  end
end
