defmodule Edenflowers.Repo.Migrations.AddOrderAmountPaid do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :amount_paid, :decimal
    end
  end

  def down do
    alter table(:orders) do
      remove :amount_paid
    end
  end
end
