defmodule Edenflowers.Repo.Migrations.AddFulfillmentOptionSortKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:fulfillment_options) do
      add :sort_key, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:fulfillment_options) do
      remove :sort_key
    end
  end
end
