defmodule Edenflowers.Repo.Migrations.AddSubscriptionSetupEmail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subscriptions) do
      add :setup_emailed_at, :utc_datetime
    end
  end

  def down do
    alter table(:subscriptions) do
      remove :setup_emailed_at
    end
  end
end
