defmodule Edenflowers.Repo.Migrations.AddCustomOrders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:line_items) do
      modify :product_image_slug, :text, null: true
      modify :product_id, :uuid, null: true
      modify :product_variant_id, :uuid, null: true
    end

    create constraint(:line_items, :line_items_catalogue_lines_have_a_product,
             check: """
               (product_variant_id IS NULL) = (product_id IS NULL)
             """
           )

    alter table(:orders) do
      add :cancelled_at, :utc_datetime
      add :origin, :text, null: false, default: "online"
      add :customer_phone_number, :text
      add :fulfillment_fee_override, :decimal
      add :payment_method, :text
      add :paid_at, :utc_datetime
      add :payment_link_token, :text
      add :details_emailed_at, :utc_datetime
      add :florist_note, :text
    end

    # Until now only checkout could pay an order, so every paid order was paid through Stripe.
    execute(
      "UPDATE orders SET payment_method = 'stripe', paid_at = ordered_at WHERE payment_status = 'paid'"
    )

    create unique_index(:orders, [:payment_link_token],
             name: "orders_unique_payment_link_token_index"
           )
  end

  def down do
    drop_if_exists unique_index(:orders, [:payment_link_token],
                     name: "orders_unique_payment_link_token_index"
                   )

    alter table(:orders) do
      remove :florist_note
      remove :details_emailed_at
      remove :payment_link_token
      remove :paid_at
      remove :payment_method
      remove :fulfillment_fee_override
      remove :customer_phone_number
      remove :origin
      remove :cancelled_at
    end

    drop_if_exists constraint(:line_items, :line_items_catalogue_lines_have_a_product)

    alter table(:line_items) do
      modify :product_variant_id, :uuid, null: false
      modify :product_id, :uuid, null: false
      modify :product_image_slug, :text, null: false
    end
  end
end
