defmodule Edenflowers.Repo.Migrations.AddFeaturedToProducts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :featured, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:products) do
      remove :featured
    end
  end
end
