defmodule Edenflowers.Repo.Migrations.AddCourseRegistrationRemovedSeats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:course_registrations) do
      add :removed_seats, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:course_registrations) do
      remove :removed_seats
    end
  end
end
