defmodule Edenflowers.Repo.Migrations.RequireDefaultedColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:course_registrations) do
      modify :status, :text, null: false
    end

    alter table(:fulfillment_options) do
      modify :same_day, :boolean, null: false
      modify :available_days, {:array, :text}, null: false
      modify :enabled_dates, {:array, :date}, null: false
      modify :disabled_dates, {:array, :date}, null: false
    end

    alter table(:line_items) do
      modify :quantity, :bigint, null: false
    end

    alter table(:orders) do
      modify :payment_status, :text, null: false
      modify :fulfillment_status, :text, null: false
      modify :gift, :boolean, null: false
      modify :locale, :text, null: false
    end

    alter table(:product_variants) do
      modify :stock_trackable, :boolean, null: false
    end
  end

  def down do
    alter table(:product_variants) do
      modify :stock_trackable, :boolean, null: true
    end

    alter table(:orders) do
      modify :locale, :text, null: true
      modify :gift, :boolean, null: true
      modify :fulfillment_status, :text, null: true
      modify :payment_status, :text, null: true
    end

    alter table(:line_items) do
      modify :quantity, :bigint, null: true
    end

    alter table(:fulfillment_options) do
      modify :disabled_dates, {:array, :date}, null: true
      modify :enabled_dates, {:array, :date}, null: true
      modify :available_days, {:array, :text}, null: true
      modify :same_day, :boolean, null: true
    end

    alter table(:course_registrations) do
      modify :status, :text, null: true
    end
  end
end
