defmodule Edenflowers.Repo.Migrations.SnapshotPromotionDiscountAndFulfillmentTaxPercentage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :fulfillment_tax_percentage, :decimal
      add :discount_percentage, :decimal
    end
  end

  def down do
    alter table(:orders) do
      remove :discount_percentage
      remove :fulfillment_tax_percentage
    end
  end
end
