defmodule Edenflowers.Repo.Migrations.AddCardDetailsToSubscriptions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subscriptions) do
      add :card_brand, :text
      add :card_last4, :text
      add :card_exp_month, :bigint
      add :card_exp_year, :bigint
    end
  end

  def down do
    alter table(:subscriptions) do
      remove :card_exp_year
      remove :card_exp_month
      remove :card_last4
      remove :card_brand
    end
  end
end
