defmodule Edenflowers.Repo.Migrations.MoveSubscriptionIntervalToLineItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:line_items) do
      add :interval_weeks, :bigint
      remove :subscribable
    end

    alter table(:orders) do
      remove :subscription_interval_weeks
    end
  end

  def down do
    alter table(:orders) do
      add :subscription_interval_weeks, :bigint
    end

    alter table(:line_items) do
      add :subscribable, :boolean, null: false, default: false
      remove :interval_weeks
    end
  end
end
