defmodule Edenflowers.Repo.Migrations.ReceiptEmailTracking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :receipt_emailed_at, :utc_datetime
      add :receipt_sha256, :text
    end
  end

  def down do
    alter table(:orders) do
      remove :receipt_sha256
      remove :receipt_emailed_at
    end
  end
end
