defmodule Edenflowers.Repo.Migrations.RestoreCourseRegistrationSeats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:course_registrations) do
      add :seats, :bigint, null: false, default: 1
    end
  end

  def down do
    alter table(:course_registrations) do
      remove :seats
    end
  end
end
