defmodule Edenflowers.Repo.Migrations.DropFulfillmentOptionMinimumCartTotal do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:fulfillment_options, :fulfillment_options_valid_minimum_cart_total)

    alter table(:fulfillment_options) do
      remove :minimum_cart_total
    end
  end

  def down do
    alter table(:fulfillment_options) do
      add :minimum_cart_total, :decimal, default: "0"
    end

    create constraint(:fulfillment_options, :fulfillment_options_valid_minimum_cart_total,
             check: """
               minimum_cart_total >= 0 AND minimum_cart_total = round(minimum_cart_total, 2)
             """
           )
  end
end
