defmodule Edenflowers.Repo.Migrations.AddDeliveredEmailedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :delivered_emailed_at, :utc_datetime
    end
  end

  def down do
    alter table(:orders) do
      remove :delivered_emailed_at
    end
  end
end
