defmodule Edenflowers.Repo.Migrations.CreateRoutesAndRouteStops do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:routes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :date, :date, null: false
      add :published_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :driver_id,
          references(:drivers,
            column: :id,
            name: "routes_driver_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:route_stops, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :sequence, :bigint, null: false
      add :status, :text, null: false, default: "pending"
      add :order_reference, :text, null: false
      add :recipient_name, :text
      add :recipient_phone, :text
      add :delivery_address, :text
      add :delivery_instructions, :text
      add :card_message, :text
      add :products, {:array, :map}, null: false, default: []
      add :position, :text
      add :leg_distance_m, :bigint, null: false
      add :leg_duration_s, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :route_id,
          references(:routes,
            column: :id,
            name: "route_stops_route_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :order_id,
          references(:orders,
            column: :id,
            name: "route_stops_order_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:route_stops, "route_stops_route_id_fkey")

    drop constraint(:route_stops, "route_stops_order_id_fkey")

    drop table(:route_stops)

    drop constraint(:routes, "routes_driver_id_fkey")

    drop table(:routes)
  end
end
