defmodule Edenflowers.Repo.Migrations.RequireNewsletterOptIn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :newsletter_opt_in, :boolean, null: false
    end
  end

  def down do
    alter table(:users) do
      modify :newsletter_opt_in, :boolean, null: true
    end
  end
end
