defmodule Edenflowers.Repo.Migrations.RetireTaxRates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:tax_rates), :archived_at, to: :retired_at
  end

  def down do
    rename table(:tax_rates), :retired_at, to: :archived_at
  end
end
