defmodule Edenflowers.Repo.Migrations.RenameMoneyFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:promotions), :discount_percentage, to: :discount_rate

    rename table(:orders), :fulfillment_amount, to: :fulfillment_fee

    rename table(:orders), :discount_percentage, to: :discount_rate
  end

  def down do
    rename table(:orders), :discount_rate, to: :discount_percentage

    rename table(:orders), :fulfillment_fee, to: :fulfillment_amount

    rename table(:promotions), :discount_rate, to: :discount_percentage
  end
end
