defmodule Edenflowers.Repo.Migrations.ModelBackgroundWork do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:course_registrations) do
      add :confirmation_emailed_at, :utc_datetime
    end

    create table(:expense_imports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :document_id, :text, null: false
      add :organization_id, :text, null: false
      add :processed_at, :utc_datetime
      add :failed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :expense_id,
          references(:expenses,
            column: :id,
            name: "expense_imports_expense_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:expense_imports, [:document_id],
             name: "expense_imports_unique_document_id_index"
           )

    alter table(:orders) do
      add :promotion_usage_counted_at, :utc_datetime
    end
  end

  def down do
    alter table(:orders) do
      remove :promotion_usage_counted_at
    end

    drop constraint(:expense_imports, "expense_imports_expense_id_fkey")

    drop_if_exists unique_index(:expense_imports, [:document_id],
                     name: "expense_imports_unique_document_id_index"
                   )

    drop table(:expense_imports)

    alter table(:course_registrations) do
      remove :confirmation_emailed_at
    end
  end
end
