defmodule Edenflowers.Repo.Migrations.AddOrderLogAndPayments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orders_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :items, :text

      add :version_source_id,
          references(:orders,
            column: :id,
            name: "orders_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:payments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :decimal, null: false
      add :method, :text, null: false
      add :payment_intent_id, :text
      add :stripe_refund_id, :text
      add :paid_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:orders,
            column: :id,
            name: "payments_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:payments, [:payment_intent_id],
             name: "payments_unique_payment_intent_index"
           )

    create unique_index(:payments, [:stripe_refund_id],
             name: "payments_unique_stripe_refund_index"
           )

    create constraint(:payments, :payments_valid_amount,
             check: """
               amount = round(amount, 2)
             """
           )

    # Until now an order held one payment: what checkout, the payment link or
    # Jennie recorded. Each paid order becomes one payment row before those
    # columns go. The PaymentIntent stays only on orders still waiting for one.
    execute("""
    INSERT INTO payments (order_id, amount, method, payment_intent_id, paid_at)
    SELECT id, amount_paid, coalesce(payment_method, 'stripe'),
           CASE WHEN coalesce(payment_method, 'stripe') = 'stripe' THEN payment_intent_id END,
           coalesce(paid_at, ordered_at, updated_at)
    FROM orders
    WHERE payment_status = 'paid' AND amount_paid IS NOT NULL
    """)

    execute("UPDATE orders SET payment_intent_id = NULL WHERE payment_status = 'paid'")

    alter table(:orders) do
      remove :payment_method
      remove :paid_at
    end

    drop_if_exists constraint(:orders, :orders_valid_amount_paid)

    drop_if_exists constraint(:orders, :orders_paid_requires_amount)

    alter table(:orders) do
      remove :amount_paid
    end
  end

  # ponytail: rolling back drops the payment rows without folding them back
  # into orders.amount_paid; write that UPDATE first if this ever needs reversing
  # on real data.
  def down do
    drop_if_exists constraint(:payments, :payments_valid_amount)

    drop constraint(:payments, "payments_order_id_fkey")

    drop_if_exists unique_index(:payments, [:stripe_refund_id],
                     name: "payments_unique_stripe_refund_index"
                   )

    drop_if_exists unique_index(:payments, [:payment_intent_id],
                     name: "payments_unique_payment_intent_index"
                   )

    drop table(:payments)

    drop constraint(:orders_versions, "orders_versions_version_source_id_fkey")

    drop table(:orders_versions)

    alter table(:orders) do
      add :amount_paid, :decimal
    end

    create constraint(:orders, :orders_paid_requires_amount,
             check: """
               payment_status != 'paid' OR amount_paid IS NOT NULL
             """
           )

    create constraint(:orders, :orders_valid_amount_paid,
             check: """
               amount_paid >= 0 AND amount_paid = round(amount_paid, 2)
             """
           )

    alter table(:orders) do
      add :paid_at, :utc_datetime
      add :payment_method, :text
    end
  end
end
