defmodule Edenflowers.Repo.Migrations.KeepSubscriptionCardOnOrder do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :stripe_customer_id, :text
      add :stripe_payment_method_id, :text
    end
  end

  def down do
    alter table(:orders) do
      remove :stripe_payment_method_id
      remove :stripe_customer_id
    end
  end
end
