defmodule Edenflowers.Repo.Migrations.RemovePaymentAttemptStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      remove :payment_attempt_status
    end
  end

  def down do
    alter table(:orders) do
      add :payment_attempt_status, :text, null: false, default: "pending"
    end
  end
end
