defmodule Edenflowers.Repo.Migrations.KeyProductFulfillmentOptionsOnPair do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("product_fulfillment_options", "product_fulfillment_options_pkey")

    execute(
      "ALTER TABLE \"product_fulfillment_options\" ADD PRIMARY KEY (product_id, fulfillment_option_id)"
    )

    alter table(:product_fulfillment_options) do
      remove :id
    end

    drop_if_exists index(:product_fulfillment_options, [:product_id])
  end

  def down do
    create index(:product_fulfillment_options, [:product_id])

    alter table(:product_fulfillment_options) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()")
    end

    execute(
      "ALTER TABLE \"product_fulfillment_options\" DROP constraint product_fulfillment_options_pkey"
    )

    execute(
      "ALTER TABLE \"product_fulfillment_options\" ADD PRIMARY KEY (id, product_id, fulfillment_option_id)"
    )
  end
end
