defmodule Edenflowers.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid, null: false
    end

    create table(:course_registrations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :email, :text, null: false
      add :seats, :bigint, null: false, default: 1
      add :removed_seats, :bigint, null: false, default: 0
      add :locale, :text, null: false, default: "sv-FI"
      add :status, :text, null: false, default: "pending"
      add :reference, :text, null: false
      add :tax_rate, :decimal, null: false
      add :amount, :decimal, null: false
      add :payment_intent_id, :text
      add :confirmed_at, :utc_datetime
      add :paid_at, :utc_datetime
      add :confirmation_emailed_at, :utc_datetime
      add :receipt_emailed_at, :utc_datetime
      add :receipt_sha256, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid
    end

    create unique_index(:course_registrations, [:reference],
             name: "course_registrations_unique_reference_index"
           )

    alter table(:course_registrations) do
      add :course_id, :uuid, null: false
    end

    create table(:courses, primary_key: false) do
      add :translations, :map
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:course_registrations) do
      modify :course_id,
             references(:courses,
               column: :id,
               name: "course_registrations_course_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:courses) do
      add :name, :text, null: false
      add :description, :text, null: false
      add :location_name, :text, null: false
      add :location_address, :text, null: false
      add :image_slug, :text, null: false
      add :date, :date, null: false
      add :start_time, :time, null: false
      add :end_time, :time, null: false
      add :register_before, :date, null: false
      add :total_places, :bigint, null: false
      add :price, :decimal, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tax_rate_id, :uuid, null: false
    end

    create table(:expense_imports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :document_id, :text, null: false
      add :organization_id, :text, null: false
      add :processed_at, :utc_datetime
      add :failed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :expense_id, :uuid
    end

    create unique_index(:expense_imports, [:document_id],
             name: "expense_imports_unique_document_id_index"
           )

    create table(:expenses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:expense_imports) do
      modify :expense_id,
             references(:expenses,
               column: :id,
               name: "expense_imports_expense_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:expenses) do
      add :document_id, :text, null: false
      add :vendor_name, :text
      add :vendor_vat_number, :text
      add :date, :date
      add :total_amount, :decimal
      add :vat_amount, :decimal
      add :currency, :text
      add :category, :text
      add :description, :text
      add :confidence, :text, null: false
      add :processed_at, :utc_datetime, null: false
      add :reviewed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:expenses, [:document_id], name: "expenses_unique_document_id_index")

    create constraint(:expenses, :expenses_valid_total_amount,
             check: """
               total_amount = round(total_amount, 2)
             """
           )

    create constraint(:expenses, :expenses_valid_vat_amount,
             check: """
               vat_amount = round(vat_amount, 2)
             """
           )

    create table(:fulfillment_options, primary_key: false) do
      add :translations, :map
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :sort_key, :bigint, null: false, default: 0
      add :fulfillment_method, :text, null: false
      add :rate_type, :text, null: false
      add :base_price, :decimal, null: false
      add :price_per_km, :decimal
      add :free_dist_km, :bigint
      add :max_dist_km, :bigint
      add :same_day, :boolean, null: false, default: false
      add :order_deadline, :time
      add :available_days, {:array, :text}, null: false
      add :enabled_dates, {:array, :date}, null: false, default: []
      add :disabled_dates, {:array, :date}, null: false, default: []
      add :tax_rate_id, :uuid, null: false
    end

    create unique_index(:fulfillment_options, [:name],
             name: "fulfillment_options_unique_name_index"
           )

    create table(:line_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :bigint, null: false, default: 1
      add :unit_price, :decimal, null: false
      add :tax_rate, :decimal, null: false
      add :product_name, :text, null: false
      add :product_image_slug, :text
      add :is_card, :boolean, null: false, default: false
      add :free_delivery, :boolean, null: false, default: false
      add :variant_size, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id, :uuid, null: false
      add :product_id, :uuid
      add :product_variant_id, :uuid
    end

    create unique_index(:line_items, [:order_id, :product_variant_id],
             name: "line_items_unique_product_variant_index"
           )

    create table(:messages, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :text, :text, null: false
      add :tool_calls, {:array, :map}
      add :tool_results, {:array, :map}
      add :source, :text, null: false, default: "user"
      add :complete, :boolean, null: false, default: true

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "messages_conversation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :response_to_id,
          references(:messages,
            column: :id,
            name: "messages_response_to_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end

    create table(:orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:line_items) do
      modify :order_id,
             references(:orders,
               column: :id,
               name: "line_items_order_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:orders) do
      add :order_reference, :text
      add :ordered_at, :utc_datetime
      add :fulfillment_status, :text, null: false, default: "pending"
      add :cancelled_at, :utc_datetime
      add :origin, :text, null: false, default: "online"
      add :customer_name, :text
      add :customer_email, :text
      add :customer_phone_number, :text
      add :gift, :boolean, null: false, default: false
      add :card_message, :text
      add :recipient_name, :text
      add :recipient_phone_number, :text
      add :delivery_address, :text
      add :delivery_instructions, :text
      add :fulfillment_date, :date
      add :quoted_fulfillment_fee, :decimal
      add :in_free_delivery_zone, :boolean
      add :fulfillment_fee_override, :decimal
      add :fulfillment_method, :text
      add :fulfillment_tax_rate, :decimal
      add :fulfillment_option_name, :text
      add :geocoded_address, :text
      add :here_id, :text
      add :distance, :bigint
      add :position, :text
      add :payment_intent_id, :text
      add :payment_link_token, :text
      add :discount_rate, :decimal
      add :promotion_name, :text
      add :promotion_code, :text
      add :promotion_minimum_cart_total, :decimal
      add :locale, :text, null: false, default: "sv-FI"
      add :receipt_emailed_at, :utc_datetime
      add :receipt_sha256, :text
      add :vat_breakdown, {:array, :map}
      add :delivered_emailed_at, :utc_datetime
      add :details_emailed_at, :utc_datetime
      add :florist_note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "contact_details"
      add :user_id, :uuid
    end

    create unique_index(:orders, [:order_reference], name: "orders_unique_order_reference_index")

    create unique_index(:orders, [:payment_link_token],
             name: "orders_unique_payment_link_token_index"
           )

    alter table(:orders) do
      add :fulfillment_option_id,
          references(:fulfillment_options,
            column: :id,
            name: "orders_fulfillment_option_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :promotion_id, :uuid
    end

    create table(:orders_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :items, :text

      add :version_source_id,
          references(:orders,
            column: :id,
            name: "orders_versions_version_source_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:payments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :decimal, null: false
      add :method, :text, null: false
      add :payment_intent_id, :text
      add :stripe_refund_id, :text
      add :paid_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :order_id,
          references(:orders,
            column: :id,
            name: "payments_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:payments, [:payment_intent_id],
             name: "payments_unique_payment_intent_index"
           )

    create unique_index(:payments, [:stripe_refund_id],
             name: "payments_unique_stripe_refund_index"
           )

    create constraint(:payments, :payments_valid_amount,
             check: """
               amount = round(amount, 2)
             """
           )

    create table(:product_categories, primary_key: false) do
      add :translations, :map
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :slug, :text, null: false
      add :visibility, :text, null: false, default: "draft"
    end

    create unique_index(:product_categories, [:slug],
             name: "product_categories_unique_slug_index"
           )

    create table(:product_variants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:line_items) do
      modify :product_variant_id,
             references(:product_variants,
               column: :id,
               name: "line_items_product_variant_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:product_variants) do
      add :price, :decimal, null: false
      add :size, :text
      add :image_slug, :text, null: false
      add :stock_trackable, :boolean, null: false, default: false
      add :stock_quantity, :bigint
      add :draft, :boolean, null: false, default: true
      add :archived_at, :utc_datetime_usec
      add :product_id, :uuid, null: false
    end

    create table(:products, primary_key: false) do
      add :translations, :map
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:line_items) do
      modify :product_id,
             references(:products,
               column: :id,
               name: "line_items_product_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create constraint(:line_items, :line_items_valid_unit_price,
             check: """
               unit_price >= 0 AND unit_price = round(unit_price, 2)
             """
           )

    create constraint(:line_items, :line_items_catalogue_lines_have_a_product,
             check: """
               (product_variant_id IS NULL) = (product_id IS NULL)
             """
           )

    alter table(:product_variants) do
      modify :product_id,
             references(:products,
               column: :id,
               name: "product_variants_product_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create constraint(:product_variants, :product_variants_valid_price,
             check: """
               (price >= 0 AND price = round(price, 2)) OR NOT ((archived_at IS NULL))
             """
           )

    alter table(:products) do
      add :name, :text, null: false
      add :image_slug, :text, null: false
      add :description, :text, null: false
      add :draft, :boolean, null: false, default: true
      add :featured, :boolean, null: false, default: false
      add :free_delivery, :boolean, null: false, default: false
      add :tax_rate_id, :uuid, null: false
    end

    create unique_index(:products, [:name], name: "products_unique_name_index")

    alter table(:products) do
      add :product_category_id,
          references(:product_categories,
            column: :id,
            name: "products_product_category_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:promotions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:orders) do
      modify :promotion_id,
             references(:promotions,
               column: :id,
               name: "orders_promotion_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:promotions) do
      add :name, :text, null: false
      add :code, :citext, null: false
      add :discount_rate, :decimal, null: false
      add :minimum_cart_total, :decimal, null: false
      add :start_date, :date
      add :expiration_date, :date
      add :usage_limit, :bigint
    end

    create unique_index(:promotions, [:code], name: "promotions_unique_code_index")

    create constraint(:promotions, :promotions_valid_minimum_cart_total,
             check: """
               minimum_cart_total >= 0 AND minimum_cart_total = round(minimum_cart_total, 2)
             """
           )

    create table(:promotions_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:tax_rates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:courses) do
      modify :tax_rate_id,
             references(:tax_rates,
               column: :id,
               name: "courses_tax_rate_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create constraint(:courses, :courses_valid_price,
             check: """
               price >= 0 AND price = round(price, 2)
             """
           )

    alter table(:fulfillment_options) do
      modify :tax_rate_id,
             references(:tax_rates,
               column: :id,
               name: "fulfillment_options_tax_rate_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create constraint(:fulfillment_options, :fulfillment_options_valid_base_price,
             check: """
               base_price >= 0 AND base_price = round(base_price, 2)
             """
           )

    create constraint(:fulfillment_options, :fulfillment_options_valid_price_per_km,
             check: """
               price_per_km >= 0 AND price_per_km = round(price_per_km, 2)
             """
           )

    alter table(:products) do
      modify :tax_rate_id,
             references(:tax_rates,
               column: :id,
               name: "products_tax_rate_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tax_rates) do
      add :name, :text, null: false
      add :percentage, :decimal, null: false
      add :retired_at, :utc_datetime_usec
    end

    create unique_index(:tax_rates, [:name], name: "tax_rates_unique_name_index")

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:conversations) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "conversations_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:course_registrations) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "course_registrations_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create constraint(:course_registrations, :course_registrations_valid_amount,
             check: """
               amount >= 0 AND amount = round(amount, 2)
             """
           )

    alter table(:orders) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "orders_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create constraint(:orders, :orders_valid_quoted_fulfillment_fee,
             check: """
               quoted_fulfillment_fee >= 0 AND quoted_fulfillment_fee = round(quoted_fulfillment_fee, 2)
             """
           )

    create constraint(:orders, :orders_valid_fulfillment_fee_override,
             check: """
               fulfillment_fee_override IS NULL OR (fulfillment_fee_override >= 0 AND fulfillment_fee_override = round(fulfillment_fee_override, 2))
             """
           )

    execute("""
    CREATE SEQUENCE reference_seq START 1400
    """)

    alter table(:users) do
      add :name, :text
      add :email, :citext, null: false
      add :newsletter_opt_in, :boolean, null: false, default: false
      add :admin, :boolean, default: false
      add :avatar, :binary
      add :avatar_content_type, :text

      add :newsletter_promo_id,
          references(:promotions,
            column: :id,
            name: "users_newsletter_promo_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")
  end

  def down do
    drop constraint(:users, "users_newsletter_promo_id_fkey")

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :newsletter_promo_id
      remove :avatar_content_type
      remove :avatar
      remove :admin
      remove :newsletter_opt_in
      remove :email
      remove :name
    end

    execute("""
    DROP SEQUENCE reference_seq
    """)

    drop_if_exists constraint(:orders, :orders_valid_fulfillment_fee_override)

    drop_if_exists constraint(:orders, :orders_valid_quoted_fulfillment_fee)

    drop constraint(:orders, "orders_promotion_id_fkey")

    drop constraint(:orders, "orders_fulfillment_option_id_fkey")

    drop constraint(:orders, "orders_user_id_fkey")

    alter table(:orders) do
      modify :user_id, :uuid
    end

    drop_if_exists constraint(:course_registrations, :course_registrations_valid_amount)

    drop constraint(:course_registrations, "course_registrations_course_id_fkey")

    drop constraint(:course_registrations, "course_registrations_user_id_fkey")

    alter table(:course_registrations) do
      modify :user_id, :uuid
    end

    drop constraint(:conversations, "conversations_user_id_fkey")

    alter table(:conversations) do
      modify :user_id, :uuid
    end

    drop table(:users)

    drop table(:tokens)

    drop_if_exists unique_index(:tax_rates, [:name], name: "tax_rates_unique_name_index")

    alter table(:tax_rates) do
      remove :retired_at
      remove :percentage
      remove :name
    end

    drop constraint(:products, "products_product_category_id_fkey")

    drop constraint(:products, "products_tax_rate_id_fkey")

    alter table(:products) do
      modify :tax_rate_id, :uuid
    end

    drop_if_exists constraint(:fulfillment_options, :fulfillment_options_valid_price_per_km)

    drop_if_exists constraint(:fulfillment_options, :fulfillment_options_valid_base_price)

    drop constraint(:fulfillment_options, "fulfillment_options_tax_rate_id_fkey")

    alter table(:fulfillment_options) do
      modify :tax_rate_id, :uuid
    end

    drop_if_exists constraint(:courses, :courses_valid_price)

    drop constraint(:courses, "courses_tax_rate_id_fkey")

    alter table(:courses) do
      modify :tax_rate_id, :uuid
    end

    drop table(:tax_rates)

    drop table(:promotions_versions)

    drop_if_exists constraint(:promotions, :promotions_valid_minimum_cart_total)

    drop_if_exists unique_index(:promotions, [:code], name: "promotions_unique_code_index")

    alter table(:promotions) do
      remove :usage_limit
      remove :expiration_date
      remove :start_date
      remove :minimum_cart_total
      remove :discount_rate
      remove :code
      remove :name
    end

    alter table(:orders) do
      modify :promotion_id, :uuid
    end

    drop table(:promotions)

    alter table(:products) do
      remove :product_category_id
    end

    drop_if_exists unique_index(:products, [:name], name: "products_unique_name_index")

    alter table(:products) do
      remove :tax_rate_id
      remove :free_delivery
      remove :featured
      remove :draft
      remove :description
      remove :image_slug
      remove :name
    end

    drop_if_exists constraint(:product_variants, :product_variants_valid_price)

    drop constraint(:product_variants, "product_variants_product_id_fkey")

    alter table(:product_variants) do
      modify :product_id, :uuid
    end

    drop_if_exists constraint(:line_items, :line_items_catalogue_lines_have_a_product)

    drop_if_exists constraint(:line_items, :line_items_valid_unit_price)

    drop constraint(:line_items, "line_items_product_variant_id_fkey")

    drop constraint(:line_items, "line_items_product_id_fkey")

    drop constraint(:line_items, "line_items_order_id_fkey")

    alter table(:line_items) do
      modify :product_id, :uuid
    end

    drop table(:products)

    alter table(:product_variants) do
      remove :product_id
      remove :archived_at
      remove :draft
      remove :stock_quantity
      remove :stock_trackable
      remove :image_slug
      remove :size
      remove :price
    end

    alter table(:line_items) do
      modify :product_variant_id, :uuid
    end

    drop table(:product_variants)

    drop_if_exists unique_index(:product_categories, [:slug],
                     name: "product_categories_unique_slug_index"
                   )

    drop table(:product_categories)

    drop_if_exists constraint(:payments, :payments_valid_amount)

    drop constraint(:payments, "payments_order_id_fkey")

    drop_if_exists unique_index(:payments, [:stripe_refund_id],
                     name: "payments_unique_stripe_refund_index"
                   )

    drop_if_exists unique_index(:payments, [:payment_intent_id],
                     name: "payments_unique_payment_intent_index"
                   )

    drop table(:payments)

    drop constraint(:orders_versions, "orders_versions_version_source_id_fkey")

    drop table(:orders_versions)

    alter table(:orders) do
      remove :promotion_id
      remove :fulfillment_option_id
    end

    drop_if_exists unique_index(:orders, [:payment_link_token],
                     name: "orders_unique_payment_link_token_index"
                   )

    drop_if_exists unique_index(:orders, [:order_reference],
                     name: "orders_unique_order_reference_index"
                   )

    alter table(:orders) do
      remove :user_id
      remove :state
      remove :updated_at
      remove :inserted_at
      remove :florist_note
      remove :details_emailed_at
      remove :delivered_emailed_at
      remove :vat_breakdown
      remove :receipt_sha256
      remove :receipt_emailed_at
      remove :locale
      remove :promotion_minimum_cart_total
      remove :promotion_code
      remove :promotion_name
      remove :discount_rate
      remove :payment_link_token
      remove :payment_intent_id
      remove :position
      remove :distance
      remove :here_id
      remove :geocoded_address
      remove :fulfillment_option_name
      remove :fulfillment_tax_rate
      remove :fulfillment_method
      remove :fulfillment_fee_override
      remove :in_free_delivery_zone
      remove :quoted_fulfillment_fee
      remove :fulfillment_date
      remove :delivery_instructions
      remove :delivery_address
      remove :recipient_phone_number
      remove :recipient_name
      remove :card_message
      remove :gift
      remove :customer_phone_number
      remove :customer_email
      remove :customer_name
      remove :origin
      remove :cancelled_at
      remove :fulfillment_status
      remove :ordered_at
      remove :order_reference
    end

    alter table(:line_items) do
      modify :order_id, :uuid
    end

    drop table(:orders)

    drop constraint(:messages, "messages_response_to_id_fkey")

    drop constraint(:messages, "messages_conversation_id_fkey")

    drop table(:messages)

    drop_if_exists unique_index(:line_items, [:order_id, :product_variant_id],
                     name: "line_items_unique_product_variant_index"
                   )

    drop table(:line_items)

    drop_if_exists unique_index(:fulfillment_options, [:name],
                     name: "fulfillment_options_unique_name_index"
                   )

    drop table(:fulfillment_options)

    drop_if_exists constraint(:expenses, :expenses_valid_vat_amount)

    drop_if_exists constraint(:expenses, :expenses_valid_total_amount)

    drop_if_exists unique_index(:expenses, [:document_id],
                     name: "expenses_unique_document_id_index"
                   )

    alter table(:expenses) do
      remove :updated_at
      remove :inserted_at
      remove :reviewed_at
      remove :processed_at
      remove :confidence
      remove :description
      remove :category
      remove :currency
      remove :vat_amount
      remove :total_amount
      remove :date
      remove :vendor_vat_number
      remove :vendor_name
      remove :document_id
    end

    drop constraint(:expense_imports, "expense_imports_expense_id_fkey")

    alter table(:expense_imports) do
      modify :expense_id, :uuid
    end

    drop table(:expenses)

    drop_if_exists unique_index(:expense_imports, [:document_id],
                     name: "expense_imports_unique_document_id_index"
                   )

    drop table(:expense_imports)

    alter table(:courses) do
      remove :tax_rate_id
      remove :updated_at
      remove :inserted_at
      remove :price
      remove :total_places
      remove :register_before
      remove :end_time
      remove :start_time
      remove :date
      remove :image_slug
      remove :location_address
      remove :location_name
      remove :description
      remove :name
    end

    alter table(:course_registrations) do
      modify :course_id, :uuid
    end

    drop table(:courses)

    alter table(:course_registrations) do
      remove :course_id
    end

    drop_if_exists unique_index(:course_registrations, [:reference],
                     name: "course_registrations_unique_reference_index"
                   )

    drop table(:course_registrations)

    drop table(:conversations)
  end
end
